// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCunWSZ1uN07au-57OD1BxaWMscuB2QIAo',
    appId: '1:976619102080:web:8ed05f328089cbe15f6b65',
    messagingSenderId: '976619102080',
    projectId: 'school-ias',
    authDomain: 'school-ias.firebaseapp.com',
    storageBucket: 'school-ias.appspot.com',
    measurementId: 'G-N9YBD4TXG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNIrOakba_DtqeY6McAbbOF8jVcKvtBog',
    appId: '1:976619102080:android:dad22aedf1e44a135f6b65',
    messagingSenderId: '976619102080',
    projectId: 'school-ias',
    storageBucket: 'school-ias.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgEQ-FDfo76ICbzJ9ZN_R842QIFPTWJ2Q',
    appId: '1:976619102080:ios:e8046f53441e61e75f6b65',
    messagingSenderId: '976619102080',
    projectId: 'school-ias',
    storageBucket: 'school-ias.appspot.com',
    iosBundleId: 'com.example.ias',
  );
}
